### ISSUE TITLE
Sync with my private s3 bucket or ftp account ?

### ISSUE THREAD

**Issue by sdusza1** [brave/sync#287] opened 2019-03-06 12:09 UTC
Would it be possible to sync with my private s3 bucket or ftp account ?

**Comment by sovanyio** [comment] 2019-03-11 18:16
Also interested in this, I'm not interested in supporting Amazon's business.

**Comment by diracdeltas** [comment] 2019-03-16 19:22
Going to close this as a dupe of #58

**Closed by diracdeltas** 2019-03-16 19:22 UTC
